### ISSUE TITLE
圖譜沒顯示

### ISSUE THREAD

**Issue by ricoisme** [AIDotNet/GraphRag.Net#18]
hi
我選擇了索引後，按下查看圖譜按鈕，但graph page看來沒呼叫後端api?
還是我漏了什麼?

謝謝

**Comment by xuzeyu91** [comment]
检查是否修改了启动端口 或者开起来vpn代理等

**Comment by ricoisme** [comment]
啟動端口沒異動，我也沒開VPN代理
![image](https://github.com/user-attachments/assets/b630ebee-48f7-4cf0-8ab4-16cedb2b4850)

**Comment by ricoisme** [comment]
OK了，GraphRag.Net.Web專案的TargetFramework，我只用net8.0，謝謝
![image](https://github.com/user-attachments/assets/474082a0-ded7-45e3-8c0f-0c8994e0e7d0)
